# Generated by Django 5.2 on 2025-05-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_alter_itens_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={},
        ),
    ]
